-----------------------------------
-- This database is to track game-level advanced stats for players from my Fifa23 career mode saves.

-- Database Design: Nearly 3NF design to eliminate data redundancy and create data consistency
-- Ultimately, a CRUD webapp will be built on top to handle write ops, so 3NF is a good approach

-- Database name: (fifa) is created in projects ./docker-compose.yaml
-- schema: will use public default
-----------------------------------

create table if not exists leagues (

    league_id int primary key generated by default as identity, -- auto-generating, no need specify on INSERT
    name text not null

);

create table if not exists teams (

    team_id int primary key generated by default as identity,
    name text not null

);

create table if not exists seasons (

    season_id int primary key generated by default as identity,
    league_id int references leagues (league_id) not null,
    team_id int references teams (team_id) not null,
    year smallint not null

);

create table if not exists players (

    player_id int primary key generated by default as identity,
    team_id int references teams (team_id) not null,
    first_name text not null,
    last_name text not null,
    birthday date

);

create table if not exists games (

    game_id int primary key generated by default as identity,
    season_id int references seasons (season_id) not null,
    game_num int not null check (game_num between 1 and 38), -- no single league/tournament has more than this
    home_or_away text not null check (home_or_away in ('home','away')),
    opp_id int references teams (team_id) not null,
    opp_goals int not null,
    opp_xg numeric(3,2) not null, -- 0.09
    opp_poss_pct numeric(4,2) not null, -- 45.8 or 45.80 or 46
    opp_shots int not null,
    my_goals int not null,
    my_xg numeric(3,2) not null,
    my_poss_pct numeric(4,2) generated always as (100 - opp_poss_pct) stored,
    my shots int not null

);

create table if not exists player_gm_drib (

    drib_id int primary key generated by default as identity

);

create table if not exists player_gm_shoot (

    shoot_id int primary key generated by default as identity

);

create table if not exists player_gm_pass (

    pass_id int primary key generated by default as identity

);

create table if not exists player_gm_def (

    def_id int primary key generated by default as identity

);




